---
title: "LMNA GWAS"
author: "Sébastien Renaut (sebastien.renaut@criucpq.ulaval.ca)"
date: "`r Sys.Date()`"
output:
  html_document:
    number_sections: F
params:
  datapath: 'C:/Users/renseb01/Documents/Steinberg_Christian/LMNA/data'
  codepath: 'C:/Users/renseb01/Documents/Steinberg_Christian/LMNA/R'
  resultspath: 'C:/Users/renseb01/Documents/Steinberg_Christian/LMNA/results'
---


```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = params$datapath)
knitr::opts_chunk$set(echo = F)
setwd(params$datapath)

library(ggplot2)
library(dplyr)
library(patchwork)
library(RColorBrewer)
library(ggrepel)
```


```{r generate a file with the sample ID with severity phenotype, along with sex covariate,eval = T}
#
chr = read.table(file.path(params$datapath,'LMNA_148_samples/chr_phased.vcf'),header  = T,sep = '\t',check.names =F,comment.char = "",skip =8)
colnames(chr)[10:ncol(chr)] = sapply(strsplit(sapply(strsplit(colnames(chr)[10:ncol(chr)],'#'),'[',2),'_'),'[',1) #simplify column names

#keep only the patients that are het. for the LMNA mutation.
temp = chr[chr$ID == 'rs267607581',]
chr = chr[,temp!= '0|0']


#clinical data
clinical = read.csv(file.path(params$datapath,'clinical/LMNA_DATA_LABELS_2025-06-25_1356.csv'),header = T)

colnames(clinical)[2] = 'id'
colnames(clinical)[colnames(clinical) == 'Severe.cardiac.phenotype..defined.as..ESHF..cardiac.mortality..ventricular.arrhythmia..severe.CMP.'] = 'severity'

family = read.csv(file.path(params$datapath,'clinical/familles.csv'),header = T,sep = '\t') 


#merge clinical + family
clinical_family = merge(clinical,family,by = 'id',all=T)
clinical_family$id = as.character(clinical_family$id)


#remove the ones I don't have genotypes for
clinical_family = clinical_family[clinical_family$id %in% colnames(chr)[10:ncol(chr)],]


#create ad data.frame that will contain info on patients.
colnames_family = merge(data.frame(id = colnames(chr)[10:ncol(chr)]),clinical_family[,colnames(clinical_family) %in% c('family_number','family','id','severity','sex')],by = 'id',all= T)
colnames_family$family[is.na(colnames_family$family)] = 'Unknown'
colnames_family$family[colnames_family$family == 'None'] = 'Unknown'
colnames_family$family_anonyme = colnames_family$family
colnames_family$severity_recoded = colnames_family$severity
colnames_family$severity_recoded[colnames_family$severity=="Yes"] = 2
colnames_family$severity_recoded[colnames_family$severity=="No"] = 1
colnames_family$sex_recoded = colnames_family$sex
colnames_family$sex_recoded[colnames_family$sex == 'Female'] = 1
colnames_family$sex_recoded[colnames_family$sex == 'Male'] = 2

colnames(colnames_family)[1] = '#IID' 

#save for plink2 --glm
write.table(colnames_family[,c(1,6,7)],file.path(params$datapath,'clinical/severe.tsv'),quote= F, sep = '\t',row.names = F)

colnames(colnames_family)[1] = 'id' 
```


# Double check the glm versus plink2 results
  * R glm and plink glm are the same, except if you apply the (default) Firth's bias reduction method for glm that don't converge (~ 1 % of samples)
```{r association, message= T}
# load plink2 results
results_gwas_plink = read.csv(file.path(params$datapath,'LMNA_52_phased/gwas_results.severity_recoded.glm.logistic.hybrid'),sep = '\t', comment.char = '', header = T)
results_gwas_plink = results_gwas_plink[!is.na(results_gwas_plink$P),]
colnames(results_gwas_plink)[c(3,16,1,2)] = c("SNP","pvalue","chr","pos")
results_plink = results_gwas_plink[results_gwas_plink$TEST == 'ADD',]
results_subset_plink = results_plink[results_plink$pvalue < 0.1,]
```

# Plot
```{r association plot, message= T}
col = c(brewer.pal(8,'Set2'),brewer.pal(9,'Set1'),brewer.pal(9,'Set3'))
col = col[c(1,9,2,11,3,10,4,12,5,13,6,14,7,15,8,16,17:27)]

###prepare data for ggplot
results_subset_forggplot <- results_subset_plink %>% 

  # Compute chromosome size
  group_by(chr) %>% 
  summarise(chr_len=max(pos)) %>% 
  
  # Calculate cumulative position of each chromosome
  mutate(tot=cumsum(as.numeric(chr_len))-as.numeric(chr_len)) %>%
  select(-chr_len) %>%
  
  # Add this info to the initial dataset
  left_join(results_subset_plink, ., by=c("chr"="chr")) %>%
  
  # Add a cumulative position of each SNP
  arrange(chr, pos) %>%
  mutate( BPcum=pos+tot)


###prepare axis labels.
axisdf = results_subset_forggplot %>%
  group_by(chr) %>%
  summarize(center=( max(BPcum) + min(BPcum) ) / 2 )

  
###prepare significant SNPs
signif = results_subset_forggplot[results_subset_forggplot$pvalue < 0.002,]
signif = results_subset_forggplot[results_subset_forggplot$SNP == 'rs2234962',]
signif$genes = 'BAG3'
print(signif)


###Make the ggplot:
manhattan_plot = ggplot(results_subset_forggplot, aes(x = BPcum, y = -log10(pvalue))) +
    
    #Show all points
    geom_point( aes(color=as.factor(chr)), alpha=0.9, size=1.3) +
    scale_color_manual(values = col) +
    
    #Custom X axis:
    scale_x_continuous(label = axisdf$chr, breaks = axisdf$center, expand = c(0.01,0.01)) +
    scale_y_continuous(breaks = c(1,2,3), labels = c(0.1,0.01,0.001), limits = c(1,3.2), expand = c(0.01,0.01))  + #remove space between plot area and x axis
    xlab('Chromosomes') + 
    ylab(bquote(italic(p)~'- value')) +
  
    #Labels
    geom_label_repel(data = signif, aes(label = genes, x = BPcum, y = -log10(pvalue)), col = col[signif$chr],  size = 4,box.padding = -0.5) +
  
    #Custom the theme:
    theme_bw() +
    
    theme( 
      legend.position="none",
      panel.border = element_blank(),
      panel.grid.major.x = element_blank(),
      panel.grid.minor.x = element_blank()) +
  
    ggtitle('Manhattan plot: SNP genotypes vs. severity phenotype (glm for severity with Sex, PC1, PC2 as covariates)')

#save plot
pdf(file.path(params$resultspath,paste0('June2025/Figure7_Manhattan_version2.pdf')),width = 10,height = 5)
manhattan_plot
dev.off()
```

# BAG3 
```{r BAG3, message= T}
clinical$BAG3 = clinical$BAG3_p.C151R..rs2234962.
clinical$BAG3[clinical$BAG3 =='AB (heterozygous)'] = 'AG (heterozygous) &\nGG (homozygous)'
clinical$BAG3[clinical$BAG3 =='BB (homozygous)'] =  'AG (heterozygous) &\nGG (homozygous)'
clinical$severity[clinical$severity =='Yes'] = 'Present'
clinical$severity[clinical$severity =='No'] = 'Absent'


###
bag3 = as.data.frame(table(clinical$BAG3,clinical$severity))
bag3 = bag3[bag3$Var2!= '',]
bag3 = bag3[bag3$Var1!= '',]
#bag3$Var2 = relevel(bag3$Var2, ref = 'Yes')
bag3$`severe\nphenotype` =bag3$Var2


#Statistical test
fisher.test(table(clinical$BAG3,clinical$severity)[2:3,2:3])


###
bag3$xlab = c(1,2,1,2) 
bag3$ylab = c(1.02,1.02,
              bag3$Freq[3]/(bag3$Freq[3]+bag3$Freq[1])+0.03,
              bag3$Freq[4]/(bag3$Freq[2]+bag3$Freq[4])+0.03)


###barplot
bag3_ggplot =
  ggplot(bag3) + 
    geom_bar(aes(fill=`severe\nphenotype`, y=Freq, x=Var1),position="fill", stat="identity") +
    geom_text(aes(label = Freq, x = xlab, y = ylab)) +
    scale_fill_brewer(palette="Paired") +
    ggtitle('BAG3 genotypes ~ severity\n(Odds-ratio of G allele = 3.6, p-value = 0.07)') +
    ylab('Frequency') +
    xlab('') +
    theme_bw()

#save plot
pdf(file.path(params$resultspath,paste0('June2025/Figure8_bag3_v2.pdf')),width = 5,height = 5)
bag3_ggplot
dev.off()
```

# BAG33 genotypes
```{r BAG3, message= T}
clinical$BAG3 = clinical$BAG3_p.C151R..rs2234962.
clinical$BAG3[clinical$BAG3 =='AB (heterozygous)'] = 'AG (heteroz.)'
clinical$BAG3[clinical$BAG3 =='BB (homozygous)'] =  'GG (homozygous)'
clinical$severity[clinical$severity =='Yes'] = 'Present'
clinical$severity[clinical$severity =='No'] = 'Absent'

###
bag3 = as.data.frame(table(clinical$BAG3,clinical$severity))
bag3 = bag3[bag3$Var2!= '',]
bag3 = bag3[bag3$Var1!= '',]
#bag3$Var2 = relevel(bag3$Var2, ref = 'Yes')
bag3$`severe\nphenotype` =bag3$Var2

###
bag3$xlab = c(1,2,3,1,2,3) 
bag3$ylab = c(1.02,1.02,1.02,
              bag3$Freq[4]/(bag3$Freq[4]+bag3$Freq[1])+0.03,
              bag3$Freq[5]/(bag3$Freq[5]+bag3$Freq[2])+0.03,
              bag3$Freq[6]/(bag3$Freq[6]+bag3$Freq[3])+0.03)



###barplot
bag3_ggplot =
  ggplot(bag3) + 
    geom_bar(aes(fill=`severe\nphenotype`, y=Freq, x=Var1),position="fill", stat="identity") +
    geom_text(aes(label = Freq, x = xlab, y = ylab)) +
    scale_fill_brewer(palette="Paired") +
    ggtitle('BAG3 genotypes ~ severity\n(Odds-ratio of G allele = 3.74, p-value = 0.10)') +
    ylab('Frequency') +
    xlab('') +
    theme_bw()

#save plot
pdf(file.path(params$resultspath,paste0('June2025/Figure8_bag3.pdf')),width = 5,height = 5)
bag3_ggplot
dev.off()
```


# session info 
```{r session test, message= T}
sessionInfo()
```
